"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import XrayStage from "@/components/skeleton/XrayStage";
import { useReplayDriver } from "@/hooks/useReplayDriver";
import { useAuth } from "@/hooks/useAuth";
import { useS3Storage } from "@/hooks/useS3Storage";
import { toReplayData, hasStarfield, type ReplayData } from "@/pipeline/overlay/replayData.mjs";

// ---------------------------------------------------------------------------
// XrayReplayDemo — the landing-page hero. It replays the scan loading-screen
// x-ray (ORB starfield + gliding skeleton + fading trail) via the shared
// XrayStage, driven by useReplayDriver.
//
// Source selection is default-first, swap-on-arrival:
//   1. render the bundled default (public/landing-demo.json) immediately — works
//      for anonymous visitors with zero auth/network wait;
//   2. if signed in, fetch the 5 newest saved runs that have a wall starfield
//      (skipping Panning captures with no orbFeatures) and cycle through them,
//      advancing to the next each time the pose loop wraps.
// Any failure leaves the default in place. The RAF/driver pauses when the canvas
// is offscreen or the tab is hidden.
// ---------------------------------------------------------------------------

/** Location of the baked default asset (regenerated by scripts/make-landing-demo.mjs). */
const DEFAULT_ASSET = "/landing-demo.json";
/** How many recent starfield-bearing runs to cycle through. */
const MAX_RUNS = 5;
/** Cap total downloads while hunting for starfield-bearing runs (Panning runs are skipped). */
const MAX_DOWNLOADS = 8;

export default function XrayReplayDemo() {
  const { user } = useAuth();
  const { listAttempts, downloadAttempt, userPrefix } = useS3Storage();
  const [defaultReplay, setDefaultReplay] = useState<ReplayData | null>(null);
  const [userReplays, setUserReplays] = useState<ReplayData[] | null>(null);
  const [active, setActive] = useState(true);
  const [activeIndex, setActiveIndex] = useState(0);
  const containerRef = useRef<HTMLDivElement>(null);

  // The playlist: the user's recent runs when available, else the bundled default.
  const replays = useMemo<ReplayData[]>(() => {
    if (userReplays && userReplays.length > 0) return userReplays;
    return defaultReplay ? [defaultReplay] : [];
  }, [userReplays, defaultReplay]);

  // Keep a ref so the (stable) loop-complete callback can read the current
  // length. When the playlist changes (default → the user's runs) a stale index
  // is tolerated: reads clamp via `activeReplay` below and the modulo here keeps
  // it in range from the next wrap on, so no reset effect is needed.
  const replaysRef = useRef<ReplayData[]>(replays);
  useEffect(() => { replaysRef.current = replays; }, [replays]);

  const handleLoopComplete = useCallback(() => {
    setActiveIndex((i) => {
      const n = replaysRef.current.length;
      return n > 0 ? (i + 1) % n : 0;
    });
  }, []);

  // 1. Default-first: load the bundled asset immediately.
  useEffect(() => {
    let mounted = true;
    fetch(DEFAULT_ASSET)
      .then((r) => (r.ok ? r.json() : null))
      .then((data: ReplayData | null) => { if (mounted && data) setDefaultReplay(data); })
      .catch(() => { /* no default asset — leave the stage blank */ });
    return () => { mounted = false; };
  }, []);

  // 2. Swap-on-arrival: signed-in users cycle their newest starfield-bearing runs.
  useEffect(() => {
    if (!user || !userPrefix) return;
    let mounted = true;
    (async () => {
      try {
        const entries = await listAttempts(`${userPrefix}/`);
        const runs = entries
          .filter((e) => /run-\d+-\w+\.json$/.test(e.key) && !e.key.endsWith(".data.json"))
          .sort((a, b) => (b.lastModified ?? "").localeCompare(a.lastModified ?? ""));
        const collected: ReplayData[] = [];
        for (const run of runs.slice(0, MAX_DOWNLOADS)) {
          const attempt = await downloadAttempt(run.key);
          if (!hasStarfield(attempt)) continue; // skip Panning captures
          collected.push(toReplayData(attempt));
          if (collected.length >= MAX_RUNS) break;
        }
        if (mounted && collected.length > 0) setUserReplays(collected);
      } catch { /* keep the default */ }
    })();
    return () => { mounted = false; };
  }, [user, userPrefix, listAttempts, downloadAttempt]);

  // Pause the loop when offscreen or the tab is hidden.
  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    let onscreen = true;
    const sync = () => setActive(onscreen && !document.hidden);
    const io = new IntersectionObserver(([entry]) => {
      onscreen = entry.isIntersecting;
      sync();
    });
    io.observe(el);
    document.addEventListener("visibilitychange", sync);
    return () => { io.disconnect(); document.removeEventListener("visibilitychange", sync); };
  }, []);

  const activeReplay = replays[activeIndex] ?? replays[0] ?? null;
  const { orbPreview, currentPose, resetSignal } = useReplayDriver(activeReplay, active, handleLoopComplete);

  const aspectStyle = useMemo(() => {
    const w = activeReplay?.aspect.w ?? 9;
    const h = activeReplay?.aspect.h ?? 16;
    return { aspectRatio: `${w} / ${h}` } as const;
  }, [activeReplay]);

  return (
    <div
      ref={containerRef}
      className="relative w-full overflow-hidden rounded-md border border-edge/40 bg-scan-stage"
      style={aspectStyle}
      aria-label="Route Scanner x-ray demo"
    >
      <XrayStage
        orbPreview={orbPreview}
        currentPose={currentPose}
        aspect={activeReplay?.aspect ?? null}
        resetSignal={resetSignal}
        className="absolute inset-0 h-full w-full object-fill"
      />
    </div>
  );
}
