"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import XrayStage from "@/components/skeleton/XrayStage";
import { useReplayDriver } from "@/hooks/useReplayDriver";
import { useAuth } from "@/hooks/useAuth";
import { useS3Storage } from "@/hooks/useS3Storage";
import { toReplayData, hasStarfield, type ReplayData } from "@/pipeline/overlay/replayData.mjs";

// ---------------------------------------------------------------------------
// XrayReplayDemo — the landing-page hero. It replays the scan loading-screen
// x-ray (ORB starfield + gliding skeleton + fading trail) via the shared
// XrayStage, driven by useReplayDriver.
//
// Source selection is default-first, swap-on-arrival:
//   1. render the bundled default (public/landing-demo.json) immediately — works
//      for anonymous visitors with zero auth/network wait;
//   2. if signed in, fetch the newest saved run that has a wall starfield
//      (skipping Panning captures with no orbFeatures) and quietly swap it in.
// Any failure leaves the default in place. The RAF/driver pauses when the canvas
// is offscreen or the tab is hidden.
// ---------------------------------------------------------------------------

/** Location of the baked default asset (regenerated by scripts/make-landing-demo.mjs). */
const DEFAULT_ASSET = "/landing-demo.json";
/** Cap how many recent runs we download while hunting for one with a starfield. */
const MAX_LOOKBACK = 3;

export default function XrayReplayDemo() {
  const { user } = useAuth();
  const { listAttempts, downloadAttempt, userPrefix } = useS3Storage();
  const [replayData, setReplayData] = useState<ReplayData | null>(null);
  const [active, setActive] = useState(true);
  const containerRef = useRef<HTMLDivElement>(null);

  // 1. Default-first: load the bundled asset immediately.
  useEffect(() => {
    let mounted = true;
    fetch(DEFAULT_ASSET)
      .then((r) => (r.ok ? r.json() : null))
      .then((data: ReplayData | null) => { if (mounted && data) setReplayData(data); })
      .catch(() => { /* no default asset — leave the stage blank */ });
    return () => { mounted = false; };
  }, []);

  // 2. Swap-on-arrival: signed-in users see their latest starfield-bearing run.
  useEffect(() => {
    if (!user || !userPrefix) return;
    let mounted = true;
    (async () => {
      try {
        const entries = await listAttempts(`${userPrefix}/`);
        const runs = entries
          .filter((e) => /run-\d+-\w+\.json$/.test(e.key) && !e.key.endsWith(".data.json"))
          .sort((a, b) => (b.lastModified ?? "").localeCompare(a.lastModified ?? ""));
        for (const run of runs.slice(0, MAX_LOOKBACK)) {
          const attempt = await downloadAttempt(run.key);
          if (!hasStarfield(attempt)) continue; // skip Panning captures
          if (mounted) setReplayData(toReplayData(attempt));
          return;
        }
      } catch { /* keep the default */ }
    })();
    return () => { mounted = false; };
  }, [user, userPrefix, listAttempts, downloadAttempt]);

  // Pause the loop when offscreen or the tab is hidden.
  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    let onscreen = true;
    const sync = () => setActive(onscreen && !document.hidden);
    const io = new IntersectionObserver(([entry]) => {
      onscreen = entry.isIntersecting;
      sync();
    });
    io.observe(el);
    document.addEventListener("visibilitychange", sync);
    return () => { io.disconnect(); document.removeEventListener("visibilitychange", sync); };
  }, []);

  const { orbPreview, currentPose, resetSignal } = useReplayDriver(replayData, active);

  const aspectStyle = useMemo(() => {
    const w = replayData?.aspect.w ?? 9;
    const h = replayData?.aspect.h ?? 16;
    return { aspectRatio: `${w} / ${h}` } as const;
  }, [replayData]);

  return (
    <div
      ref={containerRef}
      className="relative w-full max-w-xs overflow-hidden rounded-md border border-edge/40 bg-scan-stage"
      style={aspectStyle}
      aria-label="Route Scanner x-ray demo"
    >
      <XrayStage
        orbPreview={orbPreview}
        currentPose={currentPose}
        aspect={replayData?.aspect ?? null}
        resetSignal={resetSignal}
        className="absolute inset-0 h-full w-full object-fill"
      />
    </div>
  );
}
